steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$pure-loop-347420/$flaskhelloworld', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$pure-loop-347420/$flaskhelloworld']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '$flaskhelloworld', '--image', 'gcr.io/$pure-loop-347420/$flaskhelloworld', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/$pure-loop-347420/$flaskhelloworld